# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cbeb486dfbd2fe225a544a38db07675b9801cbfa9a9b58fbb266a9adfc37a1cfdc1b6e07ba20dbd264315cb59c1d511033e3a13f3c0498d737f51dc346696d4

test:
  secret_key_base: 6f86796eb4538c959d02d32d7c2c37a18fb83077a2906583f407f84385e54329cdf2f5f763037dd40d1b88af767c3b649b868bde74a251e8393b11ea1363aac6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
